// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjqiikollqinafveesvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqcWlpa29sbHFpbmFmdmVlc3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0ODQ2NjgsImV4cCI6MjA1ODA2MDY2OH0.njFCQeI6Z02X1FGlPUIEz6ueP6HMQ4PcO1-NQyXwxhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);