
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjqiikollqinafveesvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqcWlpa29sbHFpbmFmdmVlc3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0ODQ2NjgsImV4cCI6MjA1ODA2MDY2OH0.njFCQeI6Z02X1FGlPUIEz6ueP6HMQ4PcO1-NQyXwxhI";

// Supabase client with authentication configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});

// Export auth types for use in components
export type { User } from '@supabase/supabase-js';
